package ca.uhn.fhir.jpa.starter.authnz.inbound.shared;

/**
 * Following are supported by SmileCDR. We will continuously add support
 * for permission and role as needed
 * ACCESS_ADMIN_JSON ❌
 * ACCESS_ADMIN_WEB ❌
 * ACCESS_EASYSHARE ❌
 * ACCESS_FHIRWEB ❌
 * ACCESS_FHIR_ENDPOINT ✅
 * AG_ADMIN_CONSOLE_READ ❌
 * AG_ADMIN_CONSOLE_WRITE ❌
 * AG_DEV_PORTAL_READ ❌
 * AG_DEV_PORTAL_WRITE ❌
 * ARCHIVE_MODULE ❌
 * BLOCK_FHIR_READ_UNLESS_CODE_IN_VS
 * BLOCK_FHIR_READ_UNLESS_CODE_NOT_IN_VS
 * CDA_IMPORT ❌
 * CHANGE_OWN_DEFAULT_LAUNCH_CONTEXTS ❌
 * CHANGE_OWN_PASSWORD ❌
 * CHANGE_OWN_TFA_KEY ❌
 * CONTROL_MODULE ❌
 * CREATE_CDA_TEMPLATE ❌
 * CREATE_MODULE ❌
 * CREATE_USER ❌
 * DELETE_CDA_TEMPLATE ❌✅
 * DOCREF
 * DQM_QPP_BUILD
 * EASYSHARE_CREATE_SMART_HEALTH_LINK ❌
 * EMPI_ADMIN ❌
 * EMPI_UPDATE_MATCH_RULES ❌
 * EMPI_VIEW_MATCH_RULES ❌
 * ETL_IMPORT_PROCESS_FILE ❌✅
 * FHIR_ACCESS_PARTITION_ALL ✅ -> No Rules needed
 * FHIR_ACCESS_PARTITION_NAME ✅ -> No Rules neede
 * FHIR_ALL_DELETE ✅
 * FHIR_ALL_READ ✅
 * FHIR_ALL_WRITE ✅
 * FHIR_AUTO_MDM ❌
 * FHIR_BATCH ✅
 * FHIR_CAPABILITIES ✅
 * FHIR_DELETE_ALL_IN_COMPARTMENT ✅
 * FHIR_DELETE_ALL_OF_TYPE ✅
 * FHIR_DELETE_CASCADE_ALLOWED ✅
 * FHIR_DELETE_TYPE_IN_COMPARTMENT ✅
 * FHIR_DTR_USER ❌
 * FHIR_EMPI_ADMIN ❌✅
 * FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE ✅
 * FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE_OF_TYPE ✅
 * FHIR_EXTENDED_OPERATION_ON_SERVER ✅
 * FHIR_EXTENDED_OPERATION_ON_TYPE ✅
 * FHIR_EXTENDED_OPERATION_SUPERUSER ✅
 * FHIR_GET_RESOURCE_COUNTS ✅
 * FHIR_GRAPHQL ✅
 * FHIR_LIVEBUNDLE ❌
 * FHIR_MANAGE_PARTITIONS ❌
 * FHIR_MANUAL_VALIDATION ✅
 * FHIR_MDM_ADMIN ❌
 * FHIR_META_OPERATIONS_SUPERUSER✅
 * FHIR_MODIFY_SEARCH_PARAMETERS❌
 * FHIR_OP_APPLY✅
 * FHIR_OP_BINARY_ACCESS_READ✅
 * FHIR_OP_BINARY_ACCESS_WRITE✅
 * FHIR_OP_CARE_GAPS✅
 * FHIR_OP_COLLECTDATA✅
 * FHIR_OP_CQL❌
 * FHIR_OP_DATAREQUIREMENTS❌
 * FHIR_OP_EMPI_CLEAR❌
 * FHIR_OP_EMPI_DUPLICATE_PERSONS❌
 * FHIR_OP_EMPI_MERGE_PERSONS❌
 * FHIR_OP_EMPI_QUERY_LINKS❌
 * FHIR_OP_EMPI_SUBMIT❌
 * FHIR_OP_EMPI_UPDATE_LINK❌
 * FHIR_OP_ENCOUNTER_EVERYTHING✅
 * FHIR_OP_EVALUATE❌
 * FHIR_OP_EVALUATE_MEASURE✅
 * FHIR_OP_EXTRACT✅
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT❌
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT_ALL_PATIENTS❌
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT_GROUP❌
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT_PATIENT❌
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT_PATIENTS❌
 * FHIR_OP_INITIATE_BULK_DATA_EXPORT_SYSTEM❌
 * FHIR_OP_INITIATE_BULK_DATA_IMPORT❌
 * FHIR_OP_MDM_CLEAR❌
 * FHIR_OP_MDM_CREATE_LINK❌
 * FHIR_OP_MDM_DUPLICATE_GOLDEN_RESOURCES❌
 * FHIR_OP_MDM_LINK_HISTORY❌
 * FHIR_OP_MDM_MERGE_GOLDEN_RESOURCES❌
 * FHIR_OP_MDM_NOT_DUPLICATE❌
 * FHIR_OP_MDM_QUERY_LINKS❌
 * FHIR_OP_MDM_SUBMIT❌
 * FHIR_OP_MDM_UPDATE_LINK❌
 * FHIR_OP_MEMBER_MATCH✅
 * FHIR_OP_PACKAGE✅
 * FHIR_OP_PATIENT_EVERYTHING✅
 * FHIR_OP_PATIENT_EVERYTHING_ACCESS_ALL✅
 * FHIR_OP_PATIENT_MATCH✅
 * FHIR_OP_PATIENT_SUMMARY✅
 * FHIR_OP_POPULATE✅
 * FHIR_OP_PREPOPULATE❌
 * FHIR_OP_STRUCTUREDEFINITION_SNAPSHOT✅
 * FHIR_OP_SUBMIT_DATA✅
 * FHIR_PATCH✅
 * FHIR_PROCESS_MESSAGE✅
 * FHIR_READ_ALL_IN_COMPARTMENT ✅
 * FHIR_READ_ALL_OF_TYPE ✅
 * FHIR_READ_INSTANCE ✅
 * FHIR_READ_SEARCH_PARAMETERS ❌
 * FHIR_READ_TYPE_IN_COMPARTMENT ✅
 * FHIR_TRANSACTION✅
 * FHIR_TRIGGER_SUBSCRIPTION✅
 * FHIR_UPDATE_REWRITE_HISTORY✅
 * FHIR_UPLOAD_EXTERNAL_TERMINOLOGY❌
 * FHIR_WRITE_ALL_IN_COMPARTMENT ✅
 * FHIR_WRITE_ALL_OF_TYPE ✅
 * FHIR_WRITE_INSTANCE ✅
 * FHIR_WRITE_TYPE_IN_COMPARTMENT ✅
 * HFQL_EXECUTE❌
 * INVOKE_CDS_HOOKS❌
 * MANAGE_BATCH_JOBS❌
 * MDM_ADMIN❌
 * MDM_UPDATE_MATCH_RULES❌
 * MDM_VIEW_MATCH_RULES❌
 * MODULE_ADMIN❌
 * OIDC_CLIENT_PRESET_PERMISSION❌
 * OPENID_CONNECT_ADD_CLIENT❌
 * OPENID_CONNECT_ADD_SERVER❌
 * OPENID_CONNECT_EDIT_CLIENT❌
 * OPENID_CONNECT_EDIT_SERVER❌
 * OPENID_CONNECT_MANAGE_GLOBAL_SESSIONS❌
 * OPENID_CONNECT_VIEW_CLIENT_LIST❌
 * OPENID_CONNECT_VIEW_SERVER_LIST❌
 * PACKAGE_REGISTRY_READ❌
 * PACKAGE_REGISTRY_WRITE❌
 * REINSTATE_MODULE❌
 * ROLE_FHIR_TERMINOLOGY_READ_CLIENT✅
 * SAVE_USER❌
 * START_STOP_MODULE❌
 * SUBMIT_ATTACHMENT❌
 * UPDATE_MODULE_CONFIG❌
 * UPDATE_USER❌
 * USE_CDA_TEMPLATE❌
 * VIEW_AUDIT_LOG❌
 * VIEW_BATCH_JOBS❌
 * VIEW_CDA_TEMPLATE❌
 * VIEW_METRICS❌
 * VIEW_MODULE_CONFIG❌
 * VIEW_MODULE_STATUS❌
 * VIEW_TRANSACTION_LOG❌
 * VIEW_TRANSACTION_LOG_EVENT❌
 * VIEW_USERS❌
 */
public enum Permission {
    // Access
    ACCESS_FHIR_ENDPOINT,

    // ALl
    FHIR_ALL_DELETE,
    FHIR_ALL_READ,
    FHIR_ALL_WRITE,

    // Read/Write/Delete Resource
    FHIR_READ_ALL_IN_COMPARTMENT,
    FHIR_READ_ALL_OF_TYPE,
    FHIR_READ_INSTANCE,
    FHIR_READ_SEARCH_PARAMETERS,
    FHIR_READ_TYPE_IN_COMPARTMENT,
    FHIR_WRITE_ALL_IN_COMPARTMENT,
    FHIR_WRITE_ALL_OF_TYPE,
    FHIR_WRITE_INSTANCE,
    FHIR_WRITE_TYPE_IN_COMPARTMENT,
    FHIR_DELETE_ALL_IN_COMPARTMENT,
    FHIR_DELETE_ALL_OF_TYPE,
    FHIR_DELETE_CASCADE_ALLOWED,
    FHIR_DELETE_TYPE_IN_COMPARTMENT,

    // System meta Batch/Transaction
    FHIR_TRANSACTION,
    FHIR_BATCH,
    FHIR_CAPABILITIES,

    // Extended op
    FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE,
    FHIR_EXTENDED_OPERATION_ON_ANY_INSTANCE_OF_TYPE,
    FHIR_EXTENDED_OPERATION_ON_SERVER,
    FHIR_EXTENDED_OPERATION_ON_TYPE,
    FHIR_EXTENDED_OPERATION_SUPERUSER,

    // OP
    FHIR_GET_RESOURCE_COUNTS,
    FHIR_MANUAL_VALIDATION,
    FHIR_META_OPERATIONS_SUPERUSER,
    FHIR_OP_APPLY,
    FHIR_OP_BINARY_ACCESS_READ,
    FHIR_OP_BINARY_ACCESS_WRITE,
    FHIR_OP_CARE_GAPS,
    FHIR_OP_COLLECTDATA,
    FHIR_OP_SUBMIT_DATA,
    FHIR_PATCH,
    FHIR_OP_CQL,
    FHIR_OP_DATAREQUIREMENTS,
    FHIR_OP_EVALUATE_MEASURE,
    FHIR_OP_ENCOUNTER_EVERYTHING,
    FHIR_OP_EXTRACT,
    FHIR_OP_PACKAGE,
    FHIR_OP_MEMBER_MATCH,
    FHIR_OP_PATIENT_EVERYTHING,
    FHIR_OP_PATIENT_EVERYTHING_ACCESS_ALL,
    FHIR_OP_PATIENT_MATCH,
    FHIR_OP_PATIENT_SUMMARY,
    FHIR_OP_POPULATE,
    FHIR_OP_STRUCTUREDEFINITION_SNAPSHOT,
    FHIR_PROCESS_MESSAGE,
    FHIR_TRIGGER_SUBSCRIPTION,
    FHIR_UPDATE_REWRITE_HISTORY,
    FHIR_TERMINOLOGY_READ,

    // Server
    FHIR_GRAPHQL,

}